Repository splunk/ansible-role-for-splunk, pull requests merged in 2022-11, with the labels that each got.

#139 Bumped version to 9.0.1
  roles/splunk/defaults/main.yml
Labels: enhancement

#137 Explicit Group Init in Boot Config
  roles/splunk/tasks/configure_splunk_boot.yml
Labels: bug

#143 forcing usage of luseradd/lgroupadd broke some distros
  roles/splunk/defaults/main.yml
  roles/splunk/tasks/install_splunk.yml
Labels: bug

#134 feat(install): remove downloaded package after unarchive
  README.md
  roles/splunk/defaults/main.yml
  roles/splunk/tasks/download_and_unarchive.yml
Labels: enhancement

#151 reconfigure systemd if splunk was upgraded
  roles/splunk/tasks/configure_splunk_boot.yml
  roles/splunk/tasks/upgrade_splunk.yml
Labels: bug, enhancement

#155 Reset configure_boot_start var Fixes #150
  roles/splunk/tasks/main.yml
Labels: bug
